package com.example.loaiaboelsooud.pharma;

import android.app.Application;
import android.content.Context;
import android.content.res.Resources;

import java.util.HashMap;
import java.util.Map;

public class PharmaConstants extends Application {
    private static Context mContext;
    private static Resources res;

    public static final String ISFILTERED = "isFiltered";

    public static final String SELLING = "selling";
    public static final String RENTING = "renting";
    public static final String BUYING = "buying";
    public static final String PHARMACY = "pharmacy";
    public static final String WAREHOUSE = "warehouse";
    public static final String FACTORY = "factory";
    public static final String HOSPITAL = "hospital";
    public static final String LISTEDFOR = "listed_for";
    public static final String TYPE = "type";
    public static final String MANAGER = "manager";
    public static final String SECONDPHARMACIST = "second_pharmacist";
    public static final String OPENCLOSE = "open_close";
    public static final String INTERN = "intern";
    public static final String ASSISTANT = "assistant";
    public static final String PHARMACIST = "pharmacist";
    public static final String COMPANY = "company";
    public static final String WORKPLACE = "workplace";
    public static final String POSITION = "position";
    public static final String BEARER = "Bearer ";
    public static final String PROPERTIES = "properties/";
    public static final String IMAGES = "/images";
    public static final String JOBADS = "job-ads/";
    public static final String NAME = "name";
    public static final String ID = "id";
    public static final String PRESCRIPTIONS = "prescriptions/";
    public static final String AUTHORIZATION = "Authorization";
    public static final String API = "api/";
    public static final String CITIES = "city";

    public static final String ASWAN = "Aswan";
    public static final String ASYUT = "Asyut";
    public static final String LUXOR = "Luxor";
    public static final String ALEXANDRIA = "Alexandria";
    public static final String ISMAILIA = "Ismailia";
    public static final String REDSEA = "Red Sea";
    public static final String BEHEIRA = "Beheira";
    public static final String GIZA = "Giza";
    public static final String DAKAHLIA = "Dakahlia";
    public static final String SUEZ = "Suez";
    public static final String SHARQIA = "Sharqia";
    public static final String GHARBIA = "Gharbia";
    public static final String FAYOUM = "Fayoum";
    public static final String CAIRO = "Cairo";
    public static final String QALYUBIA = "Qalyubia";
    public static final String MONUFIA = "Monufia";
    public static final String MINYA = "Minya";
    public static final String NEWVALLEY = "New Valley";
    public static final String BENISUEF = "Beni Suef";
    public static final String PORTSAID = "Port Said";
    public static final String SOUTHSINAI = "South Sinai";
    public static final String DAMIETTA = "Damietta";
    public static final String SOHAG = "Sohag";
    public static final String NORTHSINAI = "North Sinai";
    public static final String QENA = "Qena";
    public static final String KAFRALSHEIKH = "Kafr al-Sheikh";
    public static final String MATRUH = "Matruh";
    public static final String NORTHCOAST = "North Coast";

    public static final String ABUQIR = "AbuQir";
    public static final String ABUTALAT = "AbuTalat";
    public static final String AGAMI = "Agami";
    public static final String ALHADRAH = "AlHadrah";
    public static final String ALIBRAHIMIYYAH = "AlIbrahimiyyah";
    public static final String AMREYA = "Amreya";
    public static final String ASAFRA = "Asafra";
    public static final String ATTARIN = "Attarin";
    public static final String AWAYED = "Awayed";
    public static final String AZARITA = "Azarita";
    public static final String BACCHUS = "Bacchus";
    public static final String BAHRAY = "Bahray";
    public static final String BOLKLY = "Bolkly";
    public static final String BORGALARAB = "Borgal_Arab";
    public static final String CAMPCEASAR = "CampCeasar";
    public static final String CLEOPATRA = "Cleopatra";
    public static final String DEKHEILA = "Dekheila";
    public static final String DHAHRIA = "Dhahria";
    public static final String ELMAX = "ElMax";
    public static final String FLEMING = "Fleming";
    public static final String GIANACLIS = "Gianaclis";
    public static final String GLIM = "Glim";
    public static final String KABBARY = "Kabbary";
    public static final String KARMOUS = "Karmous";
    public static final String KOUMALDIKKA = "Koumal-Dikka";
    public static final String LABBAN = "Labban";
    public static final String LAURENT = "Laurent";
    public static final String MAAMOURA = "MAAMOURA";
    public static final String MANDARA = "Mandara";
    public static final String MANSHIYYARAMLSTATION = "Manshiyya-ramlstation";
    public static final String MIAMI = "Miami";
    public static final String MINAALBASALKABBARY = "Minaal-basal-Kabbary";
    public static final String MOHAREMBIK = "MoharemBik";
    public static final String MONTAZAH = "Montazah";
    public static final String NAKHEEL = "Nakheel";
    public static final String NOZHA = "Nozha";
    public static final String ROUSHDY = "Roushdy";
    public static final String SABAPASHA = "Saba Pasha";
    public static final String SANSTEFANO = "San Stefano";
    public static final String SCHUTZ = "Schutz";
    public static final String SEYOUF = "Seyouf";
    public static final String SHATBY = "Shatby";
    public static final String SIDIBESHR = "SidiBeshr";
    public static final String SIDIGABER = "SidiGaber";
    public static final String SEMOUHA = "SEMOUHA";
    public static final String SPORTING = "Sporting";
    public static final String TOSSON = "Tosson";
    public static final String VICTORIA = "Victoria";
    public static final String WARDIAN = "Wardian";

    public static final String RAMDANCITY = "10th Ramdan City";
    public static final String MAY = "15 may";
    public static final String ABASIA = "Abasia";
    public static final String AINSHAMS = "Ain Shams";
    public static final String ALAMIRIYYAH = "Al Amiriyyah";
    public static final String ALMANIAL = "Al Manial";
    public static final String ALMAZAH = "Almazah";
    public static final String ATABA = "Ataba";
    public static final String BABALSHEREIA = "Bab al-Shereia";
    public static final String BAITELWATAN = "Bait  El Watan";
    public static final String BASATEEN = "Basateen";
    public static final String BOULAQ = "Boulaq";
    public static final String DARALSALAAM = "Dar al-salaam";
    public static final String DARRASA = "Darrasa";
    public static final String DOWNTOWNCAIRO = "Downtown Cairo";
    public static final String FUTURECITY = "Future City";
    public static final String GAMALEYA = "Gamaleya";
    public static final String GARDENCITY = "Garden City";
    public static final String HADAYEQALKOBBA = "Hadayeq al-kobba";
    public static final String HADAYEKHELWAN = "Hadayek Helwan";
    public static final String HELIOPLIS = "Helioplis";
    public static final String HELMEYA = "Helmeya";
    public static final String HELMEYAALGEDEDA = "Helmeya al-Gededa";
    public static final String HELWAN = "Helwan";
    public static final String IZBATANNAKHL = "Izbat an Nakhl";
    public static final String KATAMEYA = "Katameya";
    public static final String KHALIFA = "Khalifa";
    public static final String MASARA = "Masara";
    public static final String Maadi = "Maadi";
    public static final String Madinaty = "Madinaty";
    public static final String MARG = "Marg";
    public static final String MASRALKADEMA = "Masr al-Kadema";
    public static final String MATAREYA = "Matareya";
    public static final String MOKATTAM = "Mokattam";
    public static final String MOSKI = "Moski";
    public static final String MOUNIRAALGADIDA = "Mounira al-Gadida";
    public static final String MUSTURAD = "Musturad";
    public static final String NASRCITY = "Nasr City";
    public static final String NEWCAIROANDALOUS = "New Cairo -andalous";
    public static final String NEWCAIROFIFTHSETTLEMENT = "New Cairo-fifth Settlement";
    public static final String NEWCAIROFIRSTSETTLEMENT = "New Cairo -First Settlement";
    public static final String NEWCAIROLOTUS = "New Cairo -Lotus";
    public static final String NEWCAIROOTHER = "New Cairo -Other";
    public static final String NEWCAIROREHABCITY = "New Cairo -Rehab City";
    public static final String NEWCAPITALCITY = "New Capital City";
    public static final String NEWHELIOPLIS = "New Helioplis";
    public static final String NOZHACAIRO = "Nozha";
    public static final String OBOURCITY = "Obour City";
    public static final String QASRALNIL = "Qasr al-Nil";
    public static final String RAMSESRAMSEESEXTENSION = "Ramses +Ramsees Extension";
    public static final String RODALFARAG = "Rod al-Farag";
    public static final String RODA = "Roda";
    public static final String SAHEL = "Sahel";
    public static final String SALAMCITY = "Salam City";
    public static final String SAYEDAZEINAB = "Sayeda Zeinab";
    public static final String SHARABEYA = "Sharabeya";
    public static final String SHERATON = "Sheraton";
    public static final String SHOROUKCITY = "Shorouk City";
    public static final String SHUBRA = "Shubra";
    public static final String TEBEEN = "Tebeen";
    public static final String THETHIRDDISTRICT = "The 3rd District";
    public static final String TURA = "Tura";
    public static final String WAILI = "Waili";
    public static final String ZAHRAAALMAADI = "Zahraa Al Maadi";
    public static final String ZAMALEK = "Zamalek";
    public static final String ZAWYAALHAMRA = "Zawya al-Hamra";
    public static final String ZAYTOUN = "Zaytoun";
    public static final String GHAMRA = "Ghamra";
    public static final String OTHERPLACES = "other places";

    public static final String SIXTHOFOCTOBER = "6th of October";
    public static final String ABURAWASH = "Abu Rawash";
    public static final String ELAGOUZA = "El-Agouza";
    public static final String ARDELLEWA = "Ard El Lewa";
    public static final String AZIZIA = "Azizia";
    public static final String BADRASHEEN = "Badrasheen";
    public static final String BANISALAMAH = "Bani Salamah";
    public static final String BARAGIL = "Baragil";
    public static final String BASHTIL = "Bashtil";
    public static final String BOULAQDAKROUR = "Boulaq Dakrour";
    public static final String DAHABISLANDANDCOLDAIR = "Dahab Island and Coldair";
    public static final String DAHSHUR = "Dahshur";
    public static final String DOKKI = "Dokki";
    public static final String ELAYYAT = "El Ayyat";
    public static final String FAISAL = "Faisal ";
    public static final String HADAYEK6THOFOCTOBER = "Hadayek 6th of October";
    public static final String HADAYEKALAHRAM = "Hadayek al-Ahram";
    public static final String HARAM = "Haram";
    public static final String HARANEYA = "Haraneya";
    public static final String HAWAMDEYA = "Hawamdeya";
    public static final String IMBABA = "Imbaba";
    public static final String KAFRTOHORMOS = "Kafr Tohormos";
    public static final String KERDASA = "Kerdasa";
    public static final String KITKAT = "Kit Kat";
    public static final String MANSURIYYA = "Mansuriyya";
    public static final String MARKAZALGIZA = "Markaz al-Giza";
    public static final String MARYOTAYA = "Maryotaya";
    public static final String MITOQBA = "Mit Oqba";
    public static final String MOHANDESSIN = "Mohandessin";
    public static final String MONEEB = "Moneeb";
    public static final String NAHIA = "Nahia ";
    public static final String OMRANIA = "Omrania";
    public static final String OSEEM = "Oseem";
    public static final String PHARAONICVILLAGE = "Pharaonic Village";
    public static final String REMAIA = "Remaia";
    public static final String SAF = "Saf";
    public static final String SAFT = "Saft";
    public static final String SAHAFIEEN = "Sahafieen";
    public static final String SAKYETMEKKY = "Sakyet Mekky";
    public static final String SAQQARA = "Saqqara";
    public static final String SHEIKHZAYED = "Sheikh Zayed";
    public static final String SOUKALAHAD = "Souk al-Ahad";
    public static final String TERSA = "tersa";
    public static final String WARDAN = "Wardan";
    public static final String WARRAQ = "Warraq";
    public static final String WESTSOMID = "West Somid";

    public static final String ABNUB = "Abnub";
    public static final String ABUTEEG = "Abu Teeg";
    public static final String ASYUTCITY = "Asyut City";
    public static final String BADARI = "Badari";
    public static final String DAIRUT = "Dairut";
    public static final String FATEH = "Fateh";
    public static final String GHANAYEM = "Ghanayem";
    public static final String MANFALUT = "Manfalut";
    public static final String NEWASSIUT = "New Assiut";
    public static final String QUSIYA = "Qusiya";
    public static final String SAHELSELIM = "Sahel Selim";
    public static final String SEDFA = "Sedfa";

    public static final String ARMANT = "Armant";
    public static final String BAYADEYA = "Bayadeya";
    public static final String ISNA = "Isna";
    public static final String LUXORCITY = "Luxor City";
    public static final String QURNA = "Qurna";
    public static final String TOD = "Tod";
    public static final String ZINNIA = "Zinnia";

    public static final String ABUSWEAR = "Abu Swear";
    public static final String FAYED = "Fayed";
    public static final String ISMAILIACITY = "Ismailia City";
    public static final String KANTARAWEST = "Kantara West";
    public static final String QASSASEEN = "Qassaseen";
    public static final String TALALKEBEER = "Tal al-Kebeer";

    public static final String HUGHADAGOUNA = "Hughada -Gouna";
    public static final String MARSAALAM = "Marsa Alam";
    public static final String QUSAIR = "Qusair";
    public static final String RASGHARIB = "Ras Gharib";
    public static final String SAFAGA = "Safaga";
    public static final String SAHLHASHEESH = "Sahl Hasheesh";
    public static final String SHALATEENHALAYEB = "Shalateen/halayeb";
    public static final String ABURAMAD = "Abu Ramad";

    public static final String ABOUHOMS = "Abou Homs";
    public static final String ABUALMATAMER = "Abu al-Matamer";
    public static final String BADR = "Badr";
    public static final String DAMANHOUR = "Damanhour";
    public static final String DELENGAT = "Delengat";
    public static final String EDKU = "Edku";
    public static final String ETAYALBARUD = "Etay al-Barud";
    public static final String HOSHESSA = "Hosh Essa";
    public static final String KAFRALDAWWAR = "Kafr al-Dawwar";
    public static final String KOMHAMADAH = "Kom Hamadah";
    public static final String MAHMOUDIYAH = "Mahmoudiyah";
    public static final String NUBARIYAH = "Nubariyah";
    public static final String RAHMANIYA = "Rahmaniya";
    public static final String RASHID = "Rashid";
    public static final String SHUBRAKHIT = "Shubrakhit";
    public static final String WADIALNATRUN = "Wadi al-Natrun";

    public static final String AGA = "Aga";
    public static final String AKHTAB = "Akhtab";
    public static final String BANIUBAYD = "Bani Ubayd";
    public static final String BELQAS = "Belqas";
    public static final String DIKIRNIS = "Dikirnis";
    public static final String DAKAHLIAGAMALEYA = "Gamaleya";
    public static final String MANSURA = "Mansura";
    public static final String MANZALA = "Manzala";
    public static final String DAKAHLIAMATAREYA = "Matareya";
    public static final String MINATALNASR = "Minat al-Nasr";
    public static final String MITGHAMR = "Mit Ghamr";
    public static final String MITSLSEEL = "Mit Slseel";
    public static final String NABARUH = "Nabaruh";
    public static final String SHIRBIN = "Shirbin";
    public static final String SINBILLAWAIN = "Sinbillawain";
    public static final String TALKHA = "Talkha";
    public static final String TAMAALAMDEED = "Tama al-Amdeed";

    public static final String AINSUKHNA = "Ain Sukhna";
    public static final String ARBAEEN = "Arbaeen";
    public static final String ATTAKA = "Attaka ";
    public static final String SUEZFAISAL = "Faisal";
    public static final String GANAYEN = "Ganayen";

    public static final String TENTHTHOFRAMADAN = "10th of Ramadan";
    public static final String ABUHAMMMAD = "Abu Hammmad";
    public static final String ABUKABIR = "Abu Kabir";
    public static final String ALQNAYAT = "Alqnayat";
    public static final String AWLADSAQR = "Awlad Saqr";
    public static final String BILBEIS = "Bilbeis";
    public static final String DEYERBNEGM = "Deyerb Negm";
    public static final String FAQOUS = "Faqous";
    public static final String HIHYA = "Hihya";
    public static final String HUSSEINIYA = "Husseiniya";
    public static final String IBRAHEMYAH = "Ibrahemyah";
    public static final String KAFRSAQR = "Kafr Saqr ";
    public static final String MASHTOOLALSOUK = "Mashtool al-Souk";
    public static final String MINYAALQAMH = "Minya al-Qamh ";
    public static final String NEWSALHIA = "New Salhia";
    public static final String QAREEN = "Qareen";
    public static final String ZAGAZIG = "Zagazig";

    public static final String BAYSOUN = "Baysoun";
    public static final String KAFRALZAYAT = "Kafr al-Zayat";
    public static final String MAHALLAALKOBRA = "Mahalla al-Kobra";
    public static final String QUTOUR = "Qutour";
    public static final String SAMANOUD = "Samanoud";
    public static final String SANTA = "Santa";
    public static final String TANTA = "Tanta";
    public static final String ZEFTA = "Zefta";

    public static final String ATSSA = "Atssa";
    public static final String IBSHWAY = "Ibshway";
    public static final String NEWFAYOUM = "New Fayoum";
    public static final String SINNURAS = "Sinnuras";
    public static final String TAMIYA = "Tamiya";
    public static final String YUSUFALSADIQ = "Yusuf al-Sadiq";

    public static final String BAHTIM = "Bahtim";
    public static final String BANHA = "Banha";
    public static final String ELUBOUR = "El Ubour";
    public static final String KAFRSHUKR = "Kafr Shukr";
    public static final String KHANKA = "Khanka";
    public static final String KHOSOUS = "Khosous";
    public static final String QAHA = "Qaha";
    public static final String QALYUB = "Qalyub";
    public static final String QANATERALKHAIRIA = "Qanater al-Khairia";
    public static final String SHERBINALQANATER = "Sherbin al-Qanater";
    public static final String SHUBRAALKHAIMAH = "Shubra al-Khaimah";
    public static final String TOOKH = "Tookh";
    public static final String ZAWYAELNAGGAR = "Zawya El-Naggar";

    public static final String ASHMON = "Ashmon";
    public static final String BAGOUR = "Bagour";
    public static final String BERKETALSABAA = "Berket al-sabaa";
    public static final String MENOUF = "Menouf";
    public static final String MITELEZZ = "Mit El Ezz";
    public static final String QUESNA = "Quesna";
    public static final String SADAT = "Sadat";
    public static final String SERSALLYAN = "Sers al-Lyan ";
    public static final String SHEBINALKOUM = "Shebin al-Koum";
    public static final String SHOHADAA = "Shohadaa";
    public static final String TALA = "Tala";
    public static final String HAMOL = "hamol";

    public static final String ABUQURQAS = "Abu Qurqas";
    public static final String ADWA = "Adwa";
    public static final String BENIMAZAR = "Beni Mazar";
    public static final String DEIRMAWAS = "Deir Mawas";
    public static final String MAGHAGHA = "Maghagha";
    public static final String MALAWI = "Malawi";
    public static final String MATAY = "Matay";
    public static final String NEWMINYA = "New Minya";
    public static final String SAMALUT = "Samalut";

    public static final String BALAT = "Balat";
    public static final String DAKHLA = "Dakhla";
    public static final String FARAFRA = "Farafra";
    public static final String KHARGA = "Kharga";
    public static final String MUT = "Mut";
    public static final String PARIS = "Paris";

    public static final String ALFESHN = "Al Feshn";
    public static final String ALWASTY = "Al Wasty";
    public static final String BEBA = "Beba";
    public static final String EHNASIA = "Ehnasia";
    public static final String NASSAR = "Nassar";
    public static final String NEWBENISUEF = "New Beni Suef";
    public static final String SAMASTA = "Samasta";

    public static final String ARABDISTRICT = "Arab District";
    public static final String DAWAHYDISTRICT = "Dawahy District";
    public static final String GANOUBDISTRICT = "Ganoub District";
    public static final String MANAKHDISTRICT = "Manakh District";
    public static final String PORTFOUAD = "Port Fouad";
    public static final String SHARQDISTRICT = "Sharq District";
    public static final String ZOHOURDISTRICT = "Zohour District";

    public static final String ABURUDEIS = "Abu Rudeis";
    public static final String ABUZENIMAH = "Abu Zenimah";
    public static final String DAHAB = "Dahab";
    public static final String NUWEIBA = "Nuweiba";
    public static final String RASSEDR = "Ras Sedr";
    public static final String SHARMALSHEIKH = "Sharm al-Sheikh";
    public static final String STCATHERINE = "St.catherine";
    public static final String TABA = "Taba";
    public static final String TORSINAI = "Tor Sinai";

    public static final String EZBETALBURJ = "Ezbet al-Burj";
    public static final String FARESKOUR = "Fareskour";
    public static final String KAFRALBATEEKH = "Kafr al-Bateekh";
    public static final String KAFRSAAD = "Kafr Saad";
    public static final String MITABUGHALB = "Mit Abughalb";
    public static final String NEWDAMIETTA = "New Damietta";
    public static final String RASALBAR = "Ras al-Bar";
    public static final String RODAH = "Rodah";
    public static final String SARO = "Saro";
    public static final String ZARQA = "Zarqa";

    public static final String AKHMIM = "Akhmim";
    public static final String ALASIRAT = "alasirat";
    public static final String DARESSALAM = "Dar es -salam";
    public static final String GIRGA = "Girga";
    public static final String JUHAYNAH = "Juhaynah";
    public static final String MARAGHA = "Maragha";
    public static final String MONASHAA = "Monasha'a";
    public static final String SAKALTAH = "Sakaltah";
    public static final String TAHTA = "Tahta";
    public static final String TAMA = "Tama";

    public static final String ARISH = "Arish";
    public static final String BIRALABED = "Bir al-Abed";
    public static final String HASANA = "Hasana";
    public static final String NAKHL = "Nakhl";
    public static final String RAFAH = "Rafah";
    public static final String SHEIKHZOWEYED = "Sheikh Zoweyed";

    public static final String ABUTISHT = "Abu Tisht";
    public static final String FARSHOUT = "Farshout";
    public static final String KEFT = "Keft";
    public static final String NAGHAMMADI = "Nag Hammadi";
    public static final String NAKADA = "Nakada";
    public static final String KOOS = "Koos";
    public static final String ELSAMATA = "El-samata";
    public static final String DESHNA = "Deshna";
    public static final String WAKF = "Wakf";
    public static final String ELBARAHAMA = "El-barahama";
    public static final String ELASHRAF = "El-ashraf";
    public static final String QENACITY = "Qena city";
    public static final String ALKLAHIL = "Al-klahil";

    public static final String MOTOBAS = "Motobas";
    public static final String QALEEN = "Qaleen";
    public static final String RIYADH = "Riyadh";
    public static final String SIDISALEM = "Sidi Salem";
    public static final String KAFRALSHEIKHCITY = "Kafr al-Sheikh City";
    public static final String ELHAMOL = "Elhamol ";
    public static final String BELA = "Bela";
    public static final String BALTEEM = "Balteem";
    public static final String SAKHA = "Sakha";
    public static final String SEDIGHAZI = "Sedi Ghazi";

    public static final String ALAMEIN = "Alamein";
    public static final String BARANY = "Barany";
    public static final String DABAA = "Dabaa";
    public static final String HAMMAM = "Hammam";
    public static final String MARINAELALAMEIN = "Marina El Alamein";
    public static final String MARSAMATROUH = "Marsa Matrouh";
    public static final String NAGELA = "Nagela";
    public static final String SALLOUM = "Salloum";
    public static final String SIWA = "Siwa";
    public static final String RASELHEKMA = "ras el Hekma";
    public static final String SEDIABDELRAHMAN = "Sedi Abdelrahman";

    public static String[] listedForArray;
    public static String[] typeArray;
    public static String[] positionArray;
    public static String[] workPlaceArray;
    public static String[] citiesArray;

    public static String[] aswanArray;
    public static String[] asyutArray;
    public static String[] luxorArray;
    public static String[] alexandriaArray;
    public static String[] ismailiaArray;
    public static String[] redseaArray;
    public static String[] gizaArray;
    public static String[] dakahliaArray;
    public static String[] suezArray;
    public static String[] sharqiaArray;
    public static String[] gharbiaArray;
    public static String[] fayoumArray;
    public static String[] cairoArray;
    public static String[] qalyubiaArray;
    public static String[] monufiaArray;
    public static String[] minyaArray;
    public static String[] newvalleyArray;
    public static String[] benisuefArray;
    public static String[] portsaidArray;
    public static String[] southsinaiArray;
    public static String[] damiettaArray;
    public static String[] sohagArray;
    public static String[] northsinaiArray;
    public static String[] qenaArray;
    public static String[] kafralsheikhArray;
    public static String[] matruhArray;
    public static String[] northcoastArray;
    public static String[] beheiraArray;


    public static final Map<String, String> listedForMapView = new HashMap<String, String>();
    public static final Map<String, String> typeMapView = new HashMap<String, String>();
    public static final Map<String, String> positionMapView = new HashMap<String, String>();
    public static final Map<String, String> workPlaceMapView = new HashMap<String, String>();
    public static final Map<String, String> citiesMapView = new HashMap<String, String>();

    public static final Map<String, String> aswanMapView = new HashMap<String, String>();
    public static final Map<String, String> asyutMapView = new HashMap<String, String>();
    public static final Map<String, String> luxorMapView = new HashMap<String, String>();
    public static final Map<String, String> alexandriaMapView = new HashMap<String, String>();
    public static final Map<String, String> ismailiaMapView = new HashMap<String, String>();
    public static final Map<String, String> redseaMapView = new HashMap<String, String>();
    public static final Map<String, String> gizaMapView = new HashMap<String, String>();
    public static final Map<String, String> dakahliaMapView = new HashMap<String, String>();
    public static final Map<String, String> suezMapView = new HashMap<String, String>();
    public static final Map<String, String> sharqiaMapView = new HashMap<String, String>();
    public static final Map<String, String> gharbiaMapView = new HashMap<String, String>();
    public static final Map<String, String> fayoumMapView = new HashMap<String, String>();
    public static final Map<String, String> cairoMapView = new HashMap<String, String>();
    public static final Map<String, String> qalyubiaMapView = new HashMap<String, String>();
    public static final Map<String, String> monufiaMapView = new HashMap<String, String>();
    public static final Map<String, String> minyaMapView = new HashMap<String, String>();
    public static final Map<String, String> newvalleyMapView = new HashMap<String, String>();
    public static final Map<String, String> benisuefMapView = new HashMap<String, String>();
    public static final Map<String, String> portsaidMapView = new HashMap<String, String>();
    public static final Map<String, String> southsinaiMapView = new HashMap<String, String>();
    public static final Map<String, String> damiettaMapView = new HashMap<String, String>();
    public static final Map<String, String> sohagMapView = new HashMap<String, String>();
    public static final Map<String, String> northsinaiMapView = new HashMap<String, String>();
    public static final Map<String, String> qenaMapView = new HashMap<String, String>();
    public static final Map<String, String> kafralsheikhMapView = new HashMap<String, String>();
    public static final Map<String, String> matruhMapView = new HashMap<String, String>();
    public static final Map<String, String> northcoastMapView = new HashMap<String, String>();
    public static final Map<String, String> beheiraMapView = new HashMap<String, String>();


    public static final Map<String, String> positionMapAdd = new HashMap<String, String>();
    public static final Map<String, String> workPlaceMapAdd = new HashMap<String, String>();
    public static final Map<String, String> listedForMapAdd = new HashMap<String, String>();
    public static final Map<String, String> typeMapAdd = new HashMap<String, String>();
    public static final Map<String, String> citiesMapAdd = new HashMap<String, String>();
    public static final Map<String, String> aswanMapAdd = new HashMap<String, String>();
    public static final Map<String, String> asyutMapAdd = new HashMap<String, String>();
    public static final Map<String, String> luxorMapAdd = new HashMap<String, String>();
    public static final Map<String, String> alexandriaMapAdd = new HashMap<String, String>();
    public static final Map<String, String> ismailiaMapAdd = new HashMap<String, String>();
    public static final Map<String, String> redseaMapAdd = new HashMap<String, String>();
    public static final Map<String, String> gizaMapAdd = new HashMap<String, String>();
    public static final Map<String, String> dakahliaMapAdd = new HashMap<String, String>();
    public static final Map<String, String> suezMapAdd = new HashMap<String, String>();
    public static final Map<String, String> sharqiaMapAdd = new HashMap<String, String>();
    public static final Map<String, String> gharbiaMapAdd = new HashMap<String, String>();
    public static final Map<String, String> fayoumMapAdd = new HashMap<String, String>();
    public static final Map<String, String> cairoMapAdd = new HashMap<String, String>();
    public static final Map<String, String> qalyubiaMapAdd = new HashMap<String, String>();
    public static final Map<String, String> monufiaMapAdd = new HashMap<String, String>();
    public static final Map<String, String> minyaMapAdd = new HashMap<String, String>();
    public static final Map<String, String> newvalleyMapAdd = new HashMap<String, String>();
    public static final Map<String, String> benisuefMapAdd = new HashMap<String, String>();
    public static final Map<String, String> portsaidMapAdd = new HashMap<String, String>();
    public static final Map<String, String> southsinaiMapAdd = new HashMap<String, String>();
    public static final Map<String, String> damiettaMapAdd = new HashMap<String, String>();
    public static final Map<String, String> sohagMapAdd = new HashMap<String, String>();
    public static final Map<String, String> northsinaiMapAdd = new HashMap<String, String>();
    public static final Map<String, String> qenaMapAdd = new HashMap<String, String>();
    public static final Map<String, String> kafralsheikhMapAdd = new HashMap<String, String>();
    public static final Map<String, String> matruhMapAdd = new HashMap<String, String>();
    public static final Map<String, String> northcoastMapAdd = new HashMap<String, String>();
    public static final Map<String, String> beheiraMapAdd = new HashMap<String, String>();


    public PharmaConstants(Context context) {
        this.mContext = context;
        res = context.getResources();

        listedForArray = res.getStringArray(R.array.properties_listed_for_array);
        typeArray = res.getStringArray(R.array.properties_type_array);

        listedForMapView.put(SELLING, listedForArray[0]);
        listedForMapView.put(RENTING, listedForArray[1]);
        listedForMapView.put(BUYING, listedForArray[2]);

        typeMapView.put(PHARMACY, typeArray[0]);
        typeMapView.put(WAREHOUSE, typeArray[1]);
        typeMapView.put(FACTORY, typeArray[2]);
        typeMapView.put(HOSPITAL, typeArray[3]);

        listedForMapAdd.put(listedForArray[0], SELLING);
        listedForMapAdd.put(listedForArray[1], RENTING);
        listedForMapAdd.put(listedForArray[2], BUYING);

        typeMapAdd.put(typeArray[0], PHARMACY);
        typeMapAdd.put(typeArray[1], WAREHOUSE);
        typeMapAdd.put(typeArray[2], FACTORY);
        typeMapAdd.put(typeArray[3], HOSPITAL);

        positionArray = res.getStringArray(R.array.job_position_array);
        workPlaceArray = res.getStringArray(R.array.job_work_place_array);

        positionMapView.put(MANAGER, positionArray[0]);
        positionMapView.put(SECONDPHARMACIST, positionArray[1]);
        positionMapView.put(OPENCLOSE, positionArray[2]);
        positionMapView.put(INTERN, positionArray[3]);
        positionMapView.put(ASSISTANT, positionArray[4]);
        positionMapView.put(PHARMACIST, positionArray[5]);

        workPlaceMapView.put(PHARMACY, workPlaceArray[0]);
        workPlaceMapView.put(COMPANY, workPlaceArray[1]);
        workPlaceMapView.put(FACTORY, workPlaceArray[2]);
        workPlaceMapView.put(WAREHOUSE, workPlaceArray[3]);

        positionMapAdd.put(positionArray[0], MANAGER);
        positionMapAdd.put(positionArray[1], SECONDPHARMACIST);
        positionMapAdd.put(positionArray[2], OPENCLOSE);
        positionMapAdd.put(positionArray[3], INTERN);
        positionMapAdd.put(positionArray[4], ASSISTANT);
        positionMapAdd.put(positionArray[5], PHARMACIST);

        workPlaceMapAdd.put(workPlaceArray[0], PHARMACY);
        workPlaceMapAdd.put(workPlaceArray[1], COMPANY);
        workPlaceMapAdd.put(workPlaceArray[2], FACTORY);
        workPlaceMapAdd.put(workPlaceArray[3], WAREHOUSE);

        citiesArray = res.getStringArray(R.array.cities_array);

        citiesMapAdd.put(citiesArray[0], ASWAN);
        citiesMapAdd.put(citiesArray[1], ASYUT);
        citiesMapAdd.put(citiesArray[2], LUXOR);
        citiesMapAdd.put(citiesArray[3], ALEXANDRIA);
        citiesMapAdd.put(citiesArray[4], ISMAILIA);
        citiesMapAdd.put(citiesArray[5], REDSEA);
        citiesMapAdd.put(citiesArray[6], BEHEIRA);
        citiesMapAdd.put(citiesArray[7], GIZA);
        citiesMapAdd.put(citiesArray[8], DAKAHLIA);
        citiesMapAdd.put(citiesArray[9], SUEZ);
        citiesMapAdd.put(citiesArray[10], SHARQIA);
        citiesMapAdd.put(citiesArray[11], GHARBIA);
        citiesMapAdd.put(citiesArray[12], FAYOUM);
        citiesMapAdd.put(citiesArray[13], CAIRO);
        citiesMapAdd.put(citiesArray[14], QALYUBIA);
        citiesMapAdd.put(citiesArray[15], MONUFIA);
        citiesMapAdd.put(citiesArray[16], MINYA);
        citiesMapAdd.put(citiesArray[17], NEWVALLEY);
        citiesMapAdd.put(citiesArray[18], BENISUEF);
        citiesMapAdd.put(citiesArray[19], PORTSAID);
        citiesMapAdd.put(citiesArray[20], SOUTHSINAI);
        citiesMapAdd.put(citiesArray[21], DAMIETTA);
        citiesMapAdd.put(citiesArray[22], SOHAG);
        citiesMapAdd.put(citiesArray[23], NORTHSINAI);
        citiesMapAdd.put(citiesArray[24], QENA);
        citiesMapAdd.put(citiesArray[25], KAFRALSHEIKH);
        citiesMapAdd.put(citiesArray[26], MATRUH);
        citiesMapAdd.put(citiesArray[27], NORTHCOAST);

        citiesMapView.put(ASWAN, citiesArray[0]);
        citiesMapView.put(ASYUT, citiesArray[1]);
        citiesMapView.put(LUXOR, citiesArray[2]);
        citiesMapView.put(ALEXANDRIA, citiesArray[3]);
        citiesMapView.put(ISMAILIA, citiesArray[4]);
        citiesMapView.put(REDSEA, citiesArray[5]);
        citiesMapView.put(BEHEIRA, citiesArray[6]);
        citiesMapView.put(GIZA, citiesArray[7]);
        citiesMapView.put(DAKAHLIA, citiesArray[8]);
        citiesMapView.put(SUEZ, citiesArray[9]);
        citiesMapView.put(SHARQIA, citiesArray[10]);
        citiesMapView.put(GHARBIA, citiesArray[11]);
        citiesMapView.put(FAYOUM, citiesArray[12]);
        citiesMapView.put(CAIRO, citiesArray[13]);
        citiesMapView.put(QALYUBIA, citiesArray[14]);
        citiesMapView.put(MONUFIA, citiesArray[15]);
        citiesMapView.put(MINYA, citiesArray[16]);
        citiesMapView.put(NEWVALLEY, citiesArray[17]);
        citiesMapView.put(BENISUEF, citiesArray[18]);
        citiesMapView.put(PORTSAID, citiesArray[19]);
        citiesMapView.put(SOUTHSINAI, citiesArray[20]);
        citiesMapView.put(DAMIETTA, citiesArray[21]);
        citiesMapView.put(SOHAG, citiesArray[22]);
        citiesMapView.put(NORTHSINAI, citiesArray[23]);
        citiesMapView.put(QENA, citiesArray[24]);
        citiesMapView.put(KAFRALSHEIKH, citiesArray[25]);
        citiesMapView.put(MATRUH, citiesArray[26]);
        citiesMapView.put(NORTHCOAST, citiesArray[27]);

        alexandriaArray = res.getStringArray(R.array.alexandria_regions);

        alexandriaMapAdd.put(ABUQIR, alexandriaArray[0]);
        alexandriaMapAdd.put(ABUTALAT, alexandriaArray[1]);
        alexandriaMapAdd.put(AGAMI, alexandriaArray[2]);
        alexandriaMapAdd.put(ALHADRAH, alexandriaArray[3]);
        alexandriaMapAdd.put(ALIBRAHIMIYYAH, alexandriaArray[4]);
        alexandriaMapAdd.put(AMREYA, alexandriaArray[5]);
        alexandriaMapAdd.put(ASAFRA, alexandriaArray[6]);
        alexandriaMapAdd.put(ATTARIN, alexandriaArray[7]);
        alexandriaMapAdd.put(AWAYED, alexandriaArray[8]);
        alexandriaMapAdd.put(AZARITA, alexandriaArray[9]);
        alexandriaMapAdd.put(BACCHUS, alexandriaArray[10]);
        alexandriaMapAdd.put(BAHRAY, alexandriaArray[11]);
        alexandriaMapAdd.put(BOLKLY, alexandriaArray[12]);
        alexandriaMapAdd.put(BORGALARAB, alexandriaArray[13]);
        alexandriaMapAdd.put(CAMPCEASAR, alexandriaArray[14]);
        alexandriaMapAdd.put(CLEOPATRA, alexandriaArray[15]);
        alexandriaMapAdd.put(DEKHEILA, alexandriaArray[16]);
        alexandriaMapAdd.put(DHAHRIA, alexandriaArray[17]);
        alexandriaMapAdd.put(ELMAX, alexandriaArray[18]);
        alexandriaMapAdd.put(FLEMING, alexandriaArray[19]);
        alexandriaMapAdd.put(GIANACLIS, alexandriaArray[20]);
        alexandriaMapAdd.put(GLIM, alexandriaArray[21]);
        alexandriaMapAdd.put(KABBARY, alexandriaArray[22]);
        alexandriaMapAdd.put(KARMOUS, alexandriaArray[23]);
        alexandriaMapAdd.put(KOUMALDIKKA, alexandriaArray[24]);
        alexandriaMapAdd.put(LABBAN, alexandriaArray[25]);
        alexandriaMapAdd.put(LAURENT, alexandriaArray[26]);
        alexandriaMapAdd.put(MAAMOURA, alexandriaArray[27]);
        alexandriaMapAdd.put(MANDARA, alexandriaArray[28]);
        alexandriaMapAdd.put(MANSHIYYARAMLSTATION, alexandriaArray[29]);
        alexandriaMapAdd.put(MIAMI, alexandriaArray[30]);
        alexandriaMapAdd.put(MINAALBASALKABBARY, alexandriaArray[31]);
        alexandriaMapAdd.put(MOHAREMBIK, alexandriaArray[32]);
        alexandriaMapAdd.put(MONTAZAH, alexandriaArray[33]);
        alexandriaMapAdd.put(NAKHEEL, alexandriaArray[34]);
        alexandriaMapAdd.put(NOZHA, alexandriaArray[35]);
        alexandriaMapAdd.put(ROUSHDY, alexandriaArray[36]);
        alexandriaMapAdd.put(SABAPASHA, alexandriaArray[37]);
        alexandriaMapAdd.put(SANSTEFANO, alexandriaArray[38]);
        alexandriaMapAdd.put(SCHUTZ, alexandriaArray[39]);
        alexandriaMapAdd.put(SEYOUF, alexandriaArray[40]);
        alexandriaMapAdd.put(SHATBY, alexandriaArray[41]);
        alexandriaMapAdd.put(SIDIBESHR, alexandriaArray[42]);
        alexandriaMapAdd.put(SIDIGABER, alexandriaArray[43]);
        alexandriaMapAdd.put(SEMOUHA, alexandriaArray[44]);
        alexandriaMapAdd.put(SPORTING, alexandriaArray[45]);
        alexandriaMapAdd.put(TOSSON, alexandriaArray[46]);
        alexandriaMapAdd.put(VICTORIA, alexandriaArray[47]);
        alexandriaMapAdd.put(WARDIAN, alexandriaArray[48]);

        alexandriaMapView.put(alexandriaArray[0], ABUQIR);
        alexandriaMapView.put(alexandriaArray[1], ABUTALAT);
        alexandriaMapView.put(alexandriaArray[2], AGAMI);
        alexandriaMapView.put(alexandriaArray[3], ALHADRAH);
        alexandriaMapView.put(alexandriaArray[4], ALIBRAHIMIYYAH);
        alexandriaMapView.put(alexandriaArray[5], AMREYA);
        alexandriaMapView.put(alexandriaArray[6], ASAFRA);
        alexandriaMapView.put(alexandriaArray[7], ATTARIN);
        alexandriaMapView.put(alexandriaArray[8], AWAYED);
        alexandriaMapView.put(alexandriaArray[9], AZARITA);
        alexandriaMapView.put(alexandriaArray[10], BACCHUS);
        alexandriaMapView.put(alexandriaArray[11], BAHRAY);
        alexandriaMapView.put(alexandriaArray[12], BOLKLY);
        alexandriaMapView.put(alexandriaArray[13], BORGALARAB);
        alexandriaMapView.put(alexandriaArray[14], CAMPCEASAR);
        alexandriaMapView.put(alexandriaArray[15], CLEOPATRA);
        alexandriaMapView.put(alexandriaArray[16], DEKHEILA);
        alexandriaMapView.put(alexandriaArray[17], DHAHRIA);
        alexandriaMapView.put(alexandriaArray[18], ELMAX);
        alexandriaMapView.put(alexandriaArray[19], FLEMING);
        alexandriaMapView.put(alexandriaArray[20], GIANACLIS);
        alexandriaMapView.put(alexandriaArray[21], GLIM);
        alexandriaMapView.put(alexandriaArray[22], KABBARY);
        alexandriaMapView.put(alexandriaArray[23], KARMOUS);
        alexandriaMapView.put(alexandriaArray[24], KOUMALDIKKA);
        alexandriaMapView.put(alexandriaArray[25], LABBAN);
        alexandriaMapView.put(alexandriaArray[26], LAURENT);
        alexandriaMapView.put(alexandriaArray[27], MAAMOURA);
        alexandriaMapView.put(alexandriaArray[28], MANDARA);
        alexandriaMapView.put(alexandriaArray[29], MANSHIYYARAMLSTATION);
        alexandriaMapView.put(alexandriaArray[30], MIAMI);
        alexandriaMapView.put(alexandriaArray[31], MINAALBASALKABBARY);
        alexandriaMapView.put(alexandriaArray[32], MOHAREMBIK);
        alexandriaMapView.put(alexandriaArray[33], MONTAZAH);
        alexandriaMapView.put(alexandriaArray[34], NAKHEEL);
        alexandriaMapView.put(alexandriaArray[35], NOZHA);
        alexandriaMapView.put(alexandriaArray[36], ROUSHDY);
        alexandriaMapView.put(alexandriaArray[37], SABAPASHA);
        alexandriaMapView.put(alexandriaArray[38], SANSTEFANO);
        alexandriaMapView.put(alexandriaArray[39], SCHUTZ);
        alexandriaMapView.put(alexandriaArray[40], SEYOUF);
        alexandriaMapView.put(alexandriaArray[41], SHATBY);
        alexandriaMapView.put(alexandriaArray[42], SIDIBESHR);
        alexandriaMapView.put(alexandriaArray[43], SIDIGABER);
        alexandriaMapView.put(alexandriaArray[44], SEMOUHA);
        alexandriaMapView.put(alexandriaArray[45], SPORTING);
        alexandriaMapView.put(alexandriaArray[46], TOSSON);
        alexandriaMapView.put(alexandriaArray[47], VICTORIA);
        alexandriaMapView.put(alexandriaArray[48], WARDIAN);

        cairoArray = res.getStringArray(R.array.cairo_regions);

        cairoMapAdd.put(RAMDANCITY, cairoArray[0]);
        cairoMapAdd.put(MAY, cairoArray[1]);
        cairoMapAdd.put(ABASIA, cairoArray[2]);
        cairoMapAdd.put(AINSHAMS, cairoArray[3]);
        cairoMapAdd.put(ALAMIRIYYAH, cairoArray[4]);
        cairoMapAdd.put(ALMANIAL, cairoArray[5]);
        cairoMapAdd.put(ALMAZAH, cairoArray[6]);
        cairoMapAdd.put(ATABA, cairoArray[7]);
        cairoMapAdd.put(BABALSHEREIA, cairoArray[8]);
        cairoMapAdd.put(BAITELWATAN, cairoArray[9]);
        cairoMapAdd.put(BASATEEN, cairoArray[10]);
        cairoMapAdd.put(BOULAQ, cairoArray[11]);
        cairoMapAdd.put(DARALSALAAM, cairoArray[12]);
        cairoMapAdd.put(DARRASA, cairoArray[13]);
        cairoMapAdd.put(DOWNTOWNCAIRO, cairoArray[14]);
        cairoMapAdd.put(FUTURECITY, cairoArray[15]);
        cairoMapAdd.put(GAMALEYA, cairoArray[16]);
        cairoMapAdd.put(GARDENCITY, cairoArray[17]);
        cairoMapAdd.put(HADAYEQALKOBBA, cairoArray[18]);
        cairoMapAdd.put(HADAYEKHELWAN, cairoArray[19]);
        cairoMapAdd.put(HELIOPLIS, cairoArray[20]);
        cairoMapAdd.put(HELMEYA, cairoArray[21]);
        cairoMapAdd.put(HELMEYAALGEDEDA, cairoArray[22]);
        cairoMapAdd.put(HELWAN, cairoArray[23]);
        cairoMapAdd.put(IZBATANNAKHL, cairoArray[24]);
        cairoMapAdd.put(KATAMEYA, cairoArray[25]);
        cairoMapAdd.put(KHALIFA, cairoArray[26]);
        cairoMapAdd.put(MASARA, cairoArray[27]);
        cairoMapAdd.put(Maadi, cairoArray[28]);
        cairoMapAdd.put(Madinaty, cairoArray[29]);
        cairoMapAdd.put(MARG, cairoArray[30]);
        cairoMapAdd.put(MASRALKADEMA, cairoArray[31]);
        cairoMapAdd.put(MATAREYA, cairoArray[32]);
        cairoMapAdd.put(MOKATTAM, cairoArray[33]);
        cairoMapAdd.put(MOSKI, cairoArray[34]);
        cairoMapAdd.put(MOUNIRAALGADIDA, cairoArray[35]);
        cairoMapAdd.put(MUSTURAD, cairoArray[36]);
        cairoMapAdd.put(NASRCITY, cairoArray[37]);
        cairoMapAdd.put(NEWCAIROANDALOUS, cairoArray[38]);
        cairoMapAdd.put(NEWCAIROFIFTHSETTLEMENT, cairoArray[39]);
        cairoMapAdd.put(NEWCAIROFIRSTSETTLEMENT, cairoArray[40]);
        cairoMapAdd.put(NEWCAIROLOTUS, cairoArray[41]);
        cairoMapAdd.put(NEWCAIROOTHER, cairoArray[42]);
        cairoMapAdd.put(NEWCAIROREHABCITY, cairoArray[43]);
        cairoMapAdd.put(NEWCAPITALCITY, cairoArray[44]);
        cairoMapAdd.put(NEWHELIOPLIS, cairoArray[45]);
        cairoMapAdd.put(NOZHACAIRO, cairoArray[46]);
        cairoMapAdd.put(OBOURCITY, cairoArray[47]);
        cairoMapAdd.put(QASRALNIL, cairoArray[48]);
        cairoMapAdd.put(RAMSESRAMSEESEXTENSION, cairoArray[49]);
        cairoMapAdd.put(RODALFARAG, cairoArray[50]);
        cairoMapAdd.put(RODA, cairoArray[51]);
        cairoMapAdd.put(SAHEL, cairoArray[52]);
        cairoMapAdd.put(SALAMCITY, cairoArray[53]);
        cairoMapAdd.put(SAYEDAZEINAB, cairoArray[54]);
        cairoMapAdd.put(SHARABEYA, cairoArray[55]);
        cairoMapAdd.put(SHERATON, cairoArray[56]);
        cairoMapAdd.put(SHOROUKCITY, cairoArray[57]);
        cairoMapAdd.put(SHUBRA, cairoArray[58]);
        cairoMapAdd.put(TEBEEN, cairoArray[59]);
        cairoMapAdd.put(THETHIRDDISTRICT, cairoArray[60]);
        cairoMapAdd.put(TURA, cairoArray[61]);
        cairoMapAdd.put(WAILI, cairoArray[62]);
        cairoMapAdd.put(ZAHRAAALMAADI, cairoArray[63]);
        cairoMapAdd.put(ZAMALEK, cairoArray[64]);
        cairoMapAdd.put(ZAWYAALHAMRA, cairoArray[65]);
        cairoMapAdd.put(ZAYTOUN, cairoArray[66]);
        cairoMapAdd.put(GHAMRA, cairoArray[67]);
        cairoMapAdd.put(OTHERPLACES, cairoArray[68]);


        cairoMapView.put(cairoArray[0], RAMDANCITY);
        cairoMapView.put(cairoArray[1], MAY);
        cairoMapView.put(cairoArray[2], ABASIA);
        cairoMapView.put(cairoArray[3], AINSHAMS);
        cairoMapView.put(cairoArray[4], ALAMIRIYYAH);
        cairoMapView.put(cairoArray[5], ALMANIAL);
        cairoMapView.put(cairoArray[6], ALMAZAH);
        cairoMapView.put(cairoArray[7], ATABA);
        cairoMapView.put(cairoArray[8], BABALSHEREIA);
        cairoMapView.put(cairoArray[9], BAITELWATAN);
        cairoMapView.put(cairoArray[10], BASATEEN);
        cairoMapView.put(cairoArray[11], BOULAQ);
        cairoMapView.put(cairoArray[12], DARALSALAAM);
        cairoMapView.put(cairoArray[13], DARRASA);
        cairoMapView.put(cairoArray[14], DOWNTOWNCAIRO);
        cairoMapView.put(cairoArray[15], FUTURECITY);
        cairoMapView.put(cairoArray[16], GAMALEYA);
        cairoMapView.put(cairoArray[17], GARDENCITY);
        cairoMapView.put(cairoArray[18], HADAYEQALKOBBA);
        cairoMapView.put(cairoArray[19], HADAYEKHELWAN);
        cairoMapView.put(cairoArray[20], HELIOPLIS);
        cairoMapView.put(cairoArray[21], HELMEYA);
        cairoMapView.put(cairoArray[22], HELMEYAALGEDEDA);
        cairoMapView.put(cairoArray[23], HELWAN);
        cairoMapView.put(cairoArray[24], IZBATANNAKHL);
        cairoMapView.put(cairoArray[25], KATAMEYA);
        cairoMapView.put(cairoArray[26], KHALIFA);
        cairoMapView.put(cairoArray[27], MASARA);
        cairoMapView.put(cairoArray[28], Maadi);
        cairoMapView.put(cairoArray[29], Madinaty);
        cairoMapView.put(cairoArray[30], MARG);
        cairoMapView.put(cairoArray[31], MASRALKADEMA);
        cairoMapView.put(cairoArray[32], MATAREYA);
        cairoMapView.put(cairoArray[33], MOKATTAM);
        cairoMapView.put(cairoArray[34], MOSKI);
        cairoMapView.put(cairoArray[35], MOUNIRAALGADIDA);
        cairoMapView.put(cairoArray[36], MUSTURAD);
        cairoMapView.put(cairoArray[37], NASRCITY);
        cairoMapView.put(cairoArray[38], NEWCAIROANDALOUS);
        cairoMapView.put(cairoArray[39], NEWCAIROFIFTHSETTLEMENT);
        cairoMapView.put(cairoArray[40], NEWCAIROFIRSTSETTLEMENT);
        cairoMapView.put(cairoArray[41], NEWCAIROLOTUS);
        cairoMapView.put(cairoArray[42], NEWCAIROOTHER);
        cairoMapView.put(cairoArray[43], NEWCAIROREHABCITY);
        cairoMapView.put(cairoArray[44], NEWCAPITALCITY);
        cairoMapView.put(cairoArray[45], NEWHELIOPLIS);
        cairoMapView.put(cairoArray[46], NOZHACAIRO);
        cairoMapView.put(cairoArray[47], OBOURCITY);
        cairoMapView.put(cairoArray[48], QASRALNIL);
        cairoMapView.put(cairoArray[49], RAMSESRAMSEESEXTENSION);
        cairoMapView.put(cairoArray[50], RODALFARAG);
        cairoMapView.put(cairoArray[51], RODA);
        cairoMapView.put(cairoArray[52], SAHEL);
        cairoMapView.put(cairoArray[53], SALAMCITY);
        cairoMapView.put(cairoArray[54], SAYEDAZEINAB);
        cairoMapView.put(cairoArray[55], SHARABEYA);
        cairoMapView.put(cairoArray[56], SHERATON);
        cairoMapView.put(cairoArray[57], SHOROUKCITY);
        cairoMapView.put(cairoArray[58], SHUBRA);
        cairoMapView.put(cairoArray[59], TEBEEN);
        cairoMapView.put(cairoArray[60], THETHIRDDISTRICT);
        cairoMapView.put(cairoArray[61], TURA);
        cairoMapView.put(cairoArray[62], WAILI);
        cairoMapView.put(cairoArray[63], ZAHRAAALMAADI);
        cairoMapView.put(cairoArray[64], ZAMALEK);
        cairoMapView.put(cairoArray[65], ZAWYAALHAMRA);
        cairoMapView.put(cairoArray[66], ZAYTOUN);
        cairoMapView.put(cairoArray[67], GHAMRA);
        cairoMapView.put(cairoArray[68], OTHERPLACES);

        gizaArray = res.getStringArray(R.array.giza_regions);

        gizaMapAdd.put(SIXTHOFOCTOBER, gizaArray[0]);
        gizaMapAdd.put(ABURAWASH, gizaArray[1]);
        gizaMapAdd.put(ELAGOUZA, gizaArray[2]);
        gizaMapAdd.put(ARDELLEWA, gizaArray[3]);
        gizaMapAdd.put(AZIZIA, gizaArray[4]);
        gizaMapAdd.put(BADRASHEEN, gizaArray[5]);
        gizaMapAdd.put(BANISALAMAH, gizaArray[6]);
        gizaMapAdd.put(BARAGIL, gizaArray[7]);
        gizaMapAdd.put(BASHTIL, gizaArray[8]);
        gizaMapAdd.put(BOULAQDAKROUR, gizaArray[9]);
        gizaMapAdd.put(DAHABISLANDANDCOLDAIR, gizaArray[10]);
        gizaMapAdd.put(DAHSHUR, gizaArray[11]);
        gizaMapAdd.put(DOKKI, gizaArray[12]);
        gizaMapAdd.put(ELAYYAT, gizaArray[13]);
        gizaMapAdd.put(FAISAL, gizaArray[14]);
        gizaMapAdd.put(HADAYEK6THOFOCTOBER, gizaArray[15]);
        gizaMapAdd.put(HADAYEKALAHRAM, gizaArray[16]);
        gizaMapAdd.put(HARAM, gizaArray[17]);
        gizaMapAdd.put(HARANEYA, gizaArray[18]);
        gizaMapAdd.put(HAWAMDEYA, gizaArray[19]);
        gizaMapAdd.put(IMBABA, gizaArray[20]);
        gizaMapAdd.put(KAFRTOHORMOS, gizaArray[21]);
        gizaMapAdd.put(KERDASA, gizaArray[22]);
        gizaMapAdd.put(KITKAT, gizaArray[23]);
        gizaMapAdd.put(MANSURIYYA, gizaArray[24]);
        gizaMapAdd.put(MARKAZALGIZA, gizaArray[25]);
        gizaMapAdd.put(MARYOTAYA, gizaArray[26]);
        gizaMapAdd.put(MITOQBA, gizaArray[27]);
        gizaMapAdd.put(MOHANDESSIN, gizaArray[28]);
        gizaMapAdd.put(MONEEB, gizaArray[29]);
        gizaMapAdd.put(NAHIA, gizaArray[30]);
        gizaMapAdd.put(OMRANIA, gizaArray[31]);
        gizaMapAdd.put(OSEEM, gizaArray[32]);
        gizaMapAdd.put(PHARAONICVILLAGE, gizaArray[33]);
        gizaMapAdd.put(REMAIA, gizaArray[34]);
        gizaMapAdd.put(SAF, gizaArray[35]);
        gizaMapAdd.put(SAFT, gizaArray[36]);
        gizaMapAdd.put(SAHAFIEEN, gizaArray[37]);
        gizaMapAdd.put(SAKYETMEKKY, gizaArray[38]);
        gizaMapAdd.put(SAQQARA, gizaArray[39]);
        gizaMapAdd.put(SHEIKHZAYED, gizaArray[40]);
        gizaMapAdd.put(SOUKALAHAD, gizaArray[41]);
        gizaMapAdd.put(TERSA, gizaArray[42]);
        gizaMapAdd.put(WARDAN, gizaArray[43]);
        gizaMapAdd.put(WARRAQ, gizaArray[44]);
        gizaMapAdd.put(WESTSOMID, gizaArray[45]);

        gizaMapView.put(gizaArray[0], SIXTHOFOCTOBER);
        gizaMapView.put(gizaArray[1], ABURAWASH);
        gizaMapView.put(gizaArray[2], ELAGOUZA);
        gizaMapView.put(gizaArray[3], ARDELLEWA);
        gizaMapView.put(gizaArray[4], AZIZIA);
        gizaMapView.put(gizaArray[5], BADRASHEEN);
        gizaMapView.put(gizaArray[6], BANISALAMAH);
        gizaMapView.put(gizaArray[7], BARAGIL);
        gizaMapView.put(gizaArray[8], BASHTIL);
        gizaMapView.put(gizaArray[9], BOULAQDAKROUR);
        gizaMapView.put(gizaArray[10], DAHABISLANDANDCOLDAIR);
        gizaMapView.put(gizaArray[11], DAHSHUR);
        gizaMapView.put(gizaArray[12], DOKKI);
        gizaMapView.put(gizaArray[13], ELAYYAT);
        gizaMapView.put(gizaArray[14], FAISAL);
        gizaMapView.put(gizaArray[15], HADAYEK6THOFOCTOBER);
        gizaMapView.put(gizaArray[16], HADAYEKALAHRAM);
        gizaMapView.put(gizaArray[17], HARAM);
        gizaMapView.put(gizaArray[18], HARANEYA);
        gizaMapView.put(gizaArray[19], HAWAMDEYA);
        gizaMapView.put(gizaArray[20], IMBABA);
        gizaMapView.put(gizaArray[21], KAFRTOHORMOS);
        gizaMapView.put(gizaArray[22], KERDASA);
        gizaMapView.put(gizaArray[23], KITKAT);
        gizaMapView.put(gizaArray[24], MANSURIYYA);
        gizaMapView.put(gizaArray[25], MARKAZALGIZA);
        gizaMapView.put(gizaArray[26], MARYOTAYA);
        gizaMapView.put(gizaArray[27], MITOQBA);
        gizaMapView.put(gizaArray[28], MOHANDESSIN);
        gizaMapView.put(gizaArray[29], MONEEB);
        gizaMapView.put(gizaArray[30], NAHIA);
        gizaMapView.put(gizaArray[31], OMRANIA);
        gizaMapView.put(gizaArray[32], OSEEM);
        gizaMapView.put(gizaArray[33], PHARAONICVILLAGE);
        gizaMapView.put(gizaArray[34], REMAIA);
        gizaMapView.put(gizaArray[35], SAF);
        gizaMapView.put(gizaArray[36], SAFT);
        gizaMapView.put(gizaArray[37], SAHAFIEEN);
        gizaMapView.put(gizaArray[38], SAKYETMEKKY);
        gizaMapView.put(gizaArray[39], SAQQARA);
        gizaMapView.put(gizaArray[40], SHEIKHZAYED);
        gizaMapView.put(gizaArray[41], SOUKALAHAD);
        gizaMapView.put(gizaArray[42], TERSA);
        gizaMapView.put(gizaArray[43], WARDAN);
        gizaMapView.put(gizaArray[44], WARRAQ);
        gizaMapView.put(gizaArray[45], WESTSOMID);

        asyutArray = res.getStringArray(R.array.asyut_regions);

        asyutMapAdd.put(ABNUB, asyutArray[0]);
        asyutMapAdd.put(ABUTEEG, asyutArray[1]);
        asyutMapAdd.put(ASYUTCITY, asyutArray[2]);
        asyutMapAdd.put(BADARI, asyutArray[3]);
        asyutMapAdd.put(DAIRUT, asyutArray[4]);
        asyutMapAdd.put(FATEH, asyutArray[5]);
        asyutMapAdd.put(GHANAYEM, asyutArray[6]);
        asyutMapAdd.put(MANFALUT, asyutArray[7]);
        asyutMapAdd.put(NEWASSIUT, asyutArray[8]);
        asyutMapAdd.put(QUSIYA, asyutArray[9]);
        asyutMapAdd.put(SAHELSELIM, asyutArray[10]);
        asyutMapAdd.put(SEDFA, asyutArray[11]);

        asyutMapView.put(asyutArray[0], ABNUB);
        asyutMapView.put(asyutArray[1], ABUTEEG);
        asyutMapView.put(asyutArray[2], ASYUTCITY);
        asyutMapView.put(asyutArray[3], BADARI);
        asyutMapView.put(asyutArray[4], DAIRUT);
        asyutMapView.put(asyutArray[5], FATEH);
        asyutMapView.put(asyutArray[6], GHANAYEM);
        asyutMapView.put(asyutArray[7], MANFALUT);
        asyutMapView.put(asyutArray[8], NEWASSIUT);
        asyutMapView.put(asyutArray[9], QUSIYA);
        asyutMapView.put(asyutArray[10], SAHELSELIM);
        asyutMapView.put(asyutArray[11], SEDFA);

        luxorArray = res.getStringArray(R.array.luxor_regions);

        luxorMapAdd.put(ARMANT, luxorArray[0]);
        luxorMapAdd.put(BAYADEYA, luxorArray[1]);
        luxorMapAdd.put(ISNA, luxorArray[2]);
        luxorMapAdd.put(LUXORCITY, luxorArray[3]);
        luxorMapAdd.put(QURNA, luxorArray[4]);
        luxorMapAdd.put(TOD, luxorArray[5]);
        luxorMapAdd.put(ZINNIA, luxorArray[6]);

        luxorMapView.put(luxorArray[0], ARMANT);
        luxorMapView.put(luxorArray[1], BAYADEYA);
        luxorMapView.put(luxorArray[2], ISNA);
        luxorMapView.put(luxorArray[3], LUXORCITY);
        luxorMapView.put(luxorArray[4], QURNA);
        luxorMapView.put(luxorArray[5], TOD);
        luxorMapView.put(luxorArray[6], ZINNIA);

        ismailiaArray = res.getStringArray(R.array.ismailia_regions);

        ismailiaMapAdd.put(ABUSWEAR, ismailiaArray[0]);
        ismailiaMapAdd.put(FAYED, ismailiaArray[1]);
        ismailiaMapAdd.put(ISMAILIACITY, ismailiaArray[2]);
        ismailiaMapAdd.put(KANTARAWEST, ismailiaArray[3]);
        ismailiaMapAdd.put(QASSASEEN, ismailiaArray[4]);
        ismailiaMapAdd.put(TALALKEBEER, ismailiaArray[5]);

        ismailiaMapView.put(ismailiaArray[0], ABUSWEAR);
        ismailiaMapView.put(ismailiaArray[1], FAYED);
        ismailiaMapView.put(ismailiaArray[2], ISMAILIACITY);
        ismailiaMapView.put(ismailiaArray[3], KANTARAWEST);
        ismailiaMapView.put(ismailiaArray[4], QASSASEEN);
        ismailiaMapView.put(ismailiaArray[5], TALALKEBEER);

        redseaArray = res.getStringArray(R.array.redsea_regions);

        redseaMapAdd.put(HUGHADAGOUNA, redseaArray[0]);
        redseaMapAdd.put(MARSAALAM, redseaArray[1]);
        redseaMapAdd.put(QUSAIR, redseaArray[2]);
        redseaMapAdd.put(RASGHARIB, redseaArray[3]);
        redseaMapAdd.put(SAFAGA, redseaArray[4]);
        redseaMapAdd.put(SAHLHASHEESH, redseaArray[5]);
        redseaMapAdd.put(SHALATEENHALAYEB, redseaArray[6]);
        redseaMapAdd.put(ABURAMAD, redseaArray[7]);

        redseaMapView.put(redseaArray[0], HUGHADAGOUNA);
        redseaMapView.put(redseaArray[1], MARSAALAM);
        redseaMapView.put(redseaArray[2], QUSAIR);
        redseaMapView.put(redseaArray[3], RASGHARIB);
        redseaMapView.put(redseaArray[4], SAFAGA);
        redseaMapView.put(redseaArray[5], SAHLHASHEESH);
        redseaMapView.put(redseaArray[6], SHALATEENHALAYEB);
        redseaMapView.put(redseaArray[7], ABURAMAD);

        beheiraArray = res.getStringArray(R.array.behira_regions);

        beheiraMapAdd.put(ABOUHOMS, beheiraArray[0]);
        beheiraMapAdd.put(ABUALMATAMER, beheiraArray[1]);
        beheiraMapAdd.put(BADR, beheiraArray[2]);
        beheiraMapAdd.put(DAMANHOUR, beheiraArray[3]);
        beheiraMapAdd.put(DELENGAT, beheiraArray[4]);
        beheiraMapAdd.put(EDKU, beheiraArray[5]);
        beheiraMapAdd.put(ETAYALBARUD, beheiraArray[6]);
        beheiraMapAdd.put(HOSHESSA, beheiraArray[7]);
        beheiraMapAdd.put(KAFRALDAWWAR, beheiraArray[8]);
        beheiraMapAdd.put(KOMHAMADAH, beheiraArray[9]);
        beheiraMapAdd.put(MAHMOUDIYAH, beheiraArray[10]);
        beheiraMapAdd.put(NUBARIYAH, beheiraArray[11]);
        beheiraMapAdd.put(RAHMANIYA, beheiraArray[12]);
        beheiraMapAdd.put(RASHID, beheiraArray[13]);
        beheiraMapAdd.put(SHUBRAKHIT, beheiraArray[14]);
        beheiraMapAdd.put(WADIALNATRUN, beheiraArray[15]);

        beheiraMapView.put(beheiraArray[0], ABOUHOMS);
        beheiraMapView.put(beheiraArray[1], ABUALMATAMER);
        beheiraMapView.put(beheiraArray[2], BADR);
        beheiraMapView.put(beheiraArray[3], DAMANHOUR);
        beheiraMapView.put(beheiraArray[4], DELENGAT);
        beheiraMapView.put(beheiraArray[5], EDKU);
        beheiraMapView.put(beheiraArray[6], ETAYALBARUD);
        beheiraMapView.put(beheiraArray[7], HOSHESSA);
        beheiraMapView.put(beheiraArray[8], KAFRALDAWWAR);
        beheiraMapView.put(beheiraArray[9], KOMHAMADAH);
        beheiraMapView.put(beheiraArray[10], MAHMOUDIYAH);
        beheiraMapView.put(beheiraArray[11], NUBARIYAH);
        beheiraMapView.put(beheiraArray[12], RAHMANIYA);
        beheiraMapView.put(beheiraArray[13], RASHID);
        beheiraMapView.put(beheiraArray[14], SHUBRAKHIT);
        beheiraMapView.put(beheiraArray[15], WADIALNATRUN);

        dakahliaArray = res.getStringArray(R.array.dakahlia_regions);

        dakahliaMapAdd.put(AGA, dakahliaArray[0]);
        dakahliaMapAdd.put(AKHTAB, dakahliaArray[1]);
        dakahliaMapAdd.put(BANIUBAYD, dakahliaArray[2]);
        dakahliaMapAdd.put(BELQAS, dakahliaArray[3]);
        dakahliaMapAdd.put(DIKIRNIS, dakahliaArray[4]);
        dakahliaMapAdd.put(DAKAHLIAGAMALEYA, dakahliaArray[5]);
        dakahliaMapAdd.put(MANSURA, dakahliaArray[6]);
        dakahliaMapAdd.put(MANZALA, dakahliaArray[7]);
        dakahliaMapAdd.put(DAKAHLIAMATAREYA, dakahliaArray[8]);
        dakahliaMapAdd.put(MINATALNASR, dakahliaArray[9]);
        dakahliaMapAdd.put(MITGHAMR, dakahliaArray[10]);
        dakahliaMapAdd.put(MITSLSEEL, dakahliaArray[11]);
        dakahliaMapAdd.put(NABARUH, dakahliaArray[12]);
        dakahliaMapAdd.put(SHIRBIN, dakahliaArray[13]);
        dakahliaMapAdd.put(SINBILLAWAIN, dakahliaArray[14]);
        dakahliaMapAdd.put(TALKHA, dakahliaArray[15]);
        dakahliaMapAdd.put(TAMAALAMDEED, dakahliaArray[16]);

        dakahliaMapView.put(dakahliaArray[0], AGA);
        dakahliaMapView.put(dakahliaArray[1], AKHTAB);
        dakahliaMapView.put(dakahliaArray[2], BANIUBAYD);
        dakahliaMapView.put(dakahliaArray[3], BELQAS);
        dakahliaMapView.put(dakahliaArray[4], DIKIRNIS);
        dakahliaMapView.put(dakahliaArray[5], DAKAHLIAGAMALEYA);
        dakahliaMapView.put(dakahliaArray[6], MANSURA);
        dakahliaMapView.put(dakahliaArray[7], MANZALA);
        dakahliaMapView.put(dakahliaArray[8], DAKAHLIAMATAREYA);
        dakahliaMapView.put(dakahliaArray[9], MINATALNASR);
        dakahliaMapView.put(dakahliaArray[10], MITGHAMR);
        dakahliaMapView.put(dakahliaArray[11], MITSLSEEL);
        dakahliaMapView.put(dakahliaArray[12], NABARUH);
        dakahliaMapView.put(dakahliaArray[13], SHIRBIN);
        dakahliaMapView.put(dakahliaArray[14], SINBILLAWAIN);
        dakahliaMapView.put(dakahliaArray[15], TALKHA);
        dakahliaMapView.put(dakahliaArray[16], TAMAALAMDEED);

        suezArray = res.getStringArray(R.array.suez_regions);

        suezMapAdd.put(AINSUKHNA, suezArray[0]);
        suezMapAdd.put(ARBAEEN, suezArray[1]);
        suezMapAdd.put(ATTAKA, suezArray[2]);
        suezMapAdd.put(SUEZFAISAL, suezArray[3]);
        suezMapAdd.put(GANAYEN, suezArray[4]);

        suezMapView.put(suezArray[0], AINSUKHNA);
        suezMapView.put(suezArray[1], ARBAEEN);
        suezMapView.put(suezArray[2], ATTAKA);
        suezMapView.put(suezArray[3], SUEZFAISAL);
        suezMapView.put(suezArray[4], GANAYEN);

        sharqiaArray = res.getStringArray(R.array.sharqia_regions);

        sharqiaMapAdd.put(TENTHTHOFRAMADAN, sharqiaArray[0]);
        sharqiaMapAdd.put(ABUHAMMMAD, sharqiaArray[1]);
        sharqiaMapAdd.put(ABUKABIR, sharqiaArray[2]);
        sharqiaMapAdd.put(ALQNAYAT, sharqiaArray[3]);
        sharqiaMapAdd.put(AWLADSAQR, sharqiaArray[4]);
        sharqiaMapAdd.put(BILBEIS, sharqiaArray[5]);
        sharqiaMapAdd.put(DEYERBNEGM, sharqiaArray[6]);
        sharqiaMapAdd.put(FAQOUS, sharqiaArray[7]);
        sharqiaMapAdd.put(HIHYA, sharqiaArray[8]);
        sharqiaMapAdd.put(HUSSEINIYA, sharqiaArray[9]);
        sharqiaMapAdd.put(IBRAHEMYAH, sharqiaArray[10]);
        sharqiaMapAdd.put(KAFRSAQR, sharqiaArray[11]);
        sharqiaMapAdd.put(MASHTOOLALSOUK, sharqiaArray[12]);
        sharqiaMapAdd.put(MINYAALQAMH, sharqiaArray[13]);
        sharqiaMapAdd.put(NEWSALHIA, sharqiaArray[14]);
        sharqiaMapAdd.put(QAREEN, sharqiaArray[15]);
        sharqiaMapAdd.put(ZAGAZIG, sharqiaArray[16]);

        sharqiaMapView.put(sharqiaArray[0], TENTHTHOFRAMADAN);
        sharqiaMapView.put(sharqiaArray[1], ABUHAMMMAD);
        sharqiaMapView.put(sharqiaArray[2], ABUKABIR);
        sharqiaMapView.put(sharqiaArray[3], ALQNAYAT);
        sharqiaMapView.put(sharqiaArray[4], AWLADSAQR);
        sharqiaMapView.put(sharqiaArray[5], BILBEIS);
        sharqiaMapView.put(sharqiaArray[6], DEYERBNEGM);
        sharqiaMapView.put(sharqiaArray[7], FAQOUS);
        sharqiaMapView.put(sharqiaArray[8], HIHYA);
        sharqiaMapView.put(sharqiaArray[9], HUSSEINIYA);
        sharqiaMapView.put(sharqiaArray[10], IBRAHEMYAH);
        sharqiaMapView.put(sharqiaArray[11], KAFRSAQR);
        sharqiaMapView.put(sharqiaArray[12], MASHTOOLALSOUK);
        sharqiaMapView.put(sharqiaArray[13], MINYAALQAMH);
        sharqiaMapView.put(sharqiaArray[14], NEWSALHIA);
        sharqiaMapView.put(sharqiaArray[15], QAREEN);
        sharqiaMapView.put(sharqiaArray[16], ZAGAZIG);

        gharbiaArray = res.getStringArray(R.array.gharbia_regions);

        gharbiaMapAdd.put(BAYSOUN, gharbiaArray[0]);
        gharbiaMapAdd.put(KAFRALZAYAT, gharbiaArray[1]);
        gharbiaMapAdd.put(MAHALLAALKOBRA, gharbiaArray[2]);
        gharbiaMapAdd.put(QUTOUR, gharbiaArray[3]);
        gharbiaMapAdd.put(SAMANOUD, gharbiaArray[4]);
        gharbiaMapAdd.put(SANTA, gharbiaArray[5]);
        gharbiaMapAdd.put(TANTA, gharbiaArray[6]);
        gharbiaMapAdd.put(ZEFTA, gharbiaArray[7]);

        gharbiaMapView.put(gharbiaArray[0], BAYSOUN);
        gharbiaMapView.put(gharbiaArray[1], KAFRALZAYAT);
        gharbiaMapView.put(gharbiaArray[2], MAHALLAALKOBRA);
        gharbiaMapView.put(gharbiaArray[3], QUTOUR);
        gharbiaMapView.put(gharbiaArray[4], SAMANOUD);
        gharbiaMapView.put(gharbiaArray[5], SANTA);
        gharbiaMapView.put(gharbiaArray[6], TANTA);
        gharbiaMapView.put(gharbiaArray[7], ZEFTA);

        gharbiaMapView.put(gharbiaArray[0], BAYSOUN);
        gharbiaMapView.put(gharbiaArray[1], KAFRALZAYAT);
        gharbiaMapView.put(gharbiaArray[2], MAHALLAALKOBRA);
        gharbiaMapView.put(gharbiaArray[3], QUTOUR);
        gharbiaMapView.put(gharbiaArray[4], SAMANOUD);
        gharbiaMapView.put(gharbiaArray[5], SANTA);
        gharbiaMapView.put(gharbiaArray[6], TANTA);
        gharbiaMapView.put(gharbiaArray[7], ZEFTA);

        fayoumArray = res.getStringArray(R.array.fayoum_regions);

        fayoumMapAdd.put(ATSSA, fayoumArray[0]);
        fayoumMapAdd.put(IBSHWAY, fayoumArray[1]);
        fayoumMapAdd.put(NEWFAYOUM, fayoumArray[2]);
        fayoumMapAdd.put(SINNURAS, fayoumArray[3]);
        fayoumMapAdd.put(TAMIYA, fayoumArray[4]);
        fayoumMapAdd.put(YUSUFALSADIQ, fayoumArray[5]);

        fayoumMapView.put(fayoumArray[0], ATSSA);
        fayoumMapView.put(fayoumArray[1], IBSHWAY);
        fayoumMapView.put(fayoumArray[2], NEWFAYOUM);
        fayoumMapView.put(fayoumArray[3], SINNURAS);
        fayoumMapView.put(fayoumArray[4], TAMIYA);
        fayoumMapView.put(fayoumArray[5], YUSUFALSADIQ);

        qalyubiaArray = res.getStringArray(R.array.qalyubia_regions);

        qalyubiaMapAdd.put(BAHTIM, qalyubiaArray[0]);
        qalyubiaMapAdd.put(BANHA, qalyubiaArray[1]);
        qalyubiaMapAdd.put(ELUBOUR, qalyubiaArray[2]);
        qalyubiaMapAdd.put(KAFRSHUKR, qalyubiaArray[3]);
        qalyubiaMapAdd.put(KHANKA, qalyubiaArray[4]);
        qalyubiaMapAdd.put(KHOSOUS, qalyubiaArray[5]);
        qalyubiaMapAdd.put(QAHA, qalyubiaArray[6]);
        qalyubiaMapAdd.put(QALYUB, qalyubiaArray[7]);
        qalyubiaMapAdd.put(QANATERALKHAIRIA, qalyubiaArray[8]);
        qalyubiaMapAdd.put(SHERBINALQANATER, qalyubiaArray[9]);
        qalyubiaMapAdd.put(SHUBRAALKHAIMAH, qalyubiaArray[10]);
        qalyubiaMapAdd.put(TOOKH, qalyubiaArray[11]);
        qalyubiaMapAdd.put(ZAWYAELNAGGAR, qalyubiaArray[12]);

        qalyubiaMapView.put(qalyubiaArray[0], BAHTIM);
        qalyubiaMapView.put(qalyubiaArray[1], BANHA);
        qalyubiaMapView.put(qalyubiaArray[2], ELUBOUR);
        qalyubiaMapView.put(qalyubiaArray[3], KAFRSHUKR);
        qalyubiaMapView.put(qalyubiaArray[4], KHANKA);
        qalyubiaMapView.put(qalyubiaArray[5], KHOSOUS);
        qalyubiaMapView.put(qalyubiaArray[6], QAHA);
        qalyubiaMapView.put(qalyubiaArray[7], QALYUB);
        qalyubiaMapView.put(qalyubiaArray[8], QANATERALKHAIRIA);
        qalyubiaMapView.put(qalyubiaArray[9], SHERBINALQANATER);
        qalyubiaMapView.put(qalyubiaArray[10], SHUBRAALKHAIMAH);
        qalyubiaMapView.put(qalyubiaArray[11], TOOKH);
        qalyubiaMapView.put(qalyubiaArray[12], ZAWYAELNAGGAR);

        monufiaArray = res.getStringArray(R.array.monufia_regions);

        monufiaMapAdd.put(ASHMON, monufiaArray[0]);
        monufiaMapAdd.put(BAGOUR, monufiaArray[1]);
        monufiaMapAdd.put(BERKETALSABAA, monufiaArray[2]);
        monufiaMapAdd.put(MENOUF, monufiaArray[3]);
        monufiaMapAdd.put(MITELEZZ, monufiaArray[4]);
        monufiaMapAdd.put(QUESNA, monufiaArray[5]);
        monufiaMapAdd.put(SADAT, monufiaArray[6]);
        monufiaMapAdd.put(SERSALLYAN, monufiaArray[7]);
        monufiaMapAdd.put(SHEBINALKOUM, monufiaArray[8]);
        monufiaMapAdd.put(SHOHADAA, monufiaArray[9]);
        monufiaMapAdd.put(TALA, monufiaArray[10]);
        monufiaMapAdd.put(HAMOL, monufiaArray[11]);

        monufiaMapView.put(monufiaArray[0], ASHMON);
        monufiaMapView.put(monufiaArray[1], BAGOUR);
        monufiaMapView.put(monufiaArray[2], BERKETALSABAA);
        monufiaMapView.put(monufiaArray[3], MENOUF);
        monufiaMapView.put(monufiaArray[4], MITELEZZ);
        monufiaMapView.put(monufiaArray[5], QUESNA);
        monufiaMapView.put(monufiaArray[6], SADAT);
        monufiaMapView.put(monufiaArray[7], SERSALLYAN);
        monufiaMapView.put(monufiaArray[8], SHEBINALKOUM);
        monufiaMapView.put(monufiaArray[9], SHOHADAA);
        monufiaMapView.put(monufiaArray[10], TALA);
        monufiaMapView.put(monufiaArray[11], HAMOL);


        minyaArray = res.getStringArray(R.array.minya_regions);

        minyaMapAdd.put(ABUQURQAS, minyaArray[0]);
        minyaMapAdd.put(ADWA, minyaArray[1]);
        minyaMapAdd.put(BENIMAZAR, minyaArray[2]);
        minyaMapAdd.put(DEIRMAWAS, minyaArray[3]);
        minyaMapAdd.put(MAGHAGHA, minyaArray[4]);
        minyaMapAdd.put(MALAWI, minyaArray[5]);
        minyaMapAdd.put(MATAY, minyaArray[6]);
        minyaMapAdd.put(NEWMINYA, minyaArray[7]);
        minyaMapAdd.put(SAMALUT, minyaArray[8]);

        minyaMapView.put(minyaArray[0], ABUQURQAS);
        minyaMapView.put(minyaArray[1], ADWA);
        minyaMapView.put(minyaArray[2], BENIMAZAR);
        minyaMapView.put(minyaArray[3], DEIRMAWAS);
        minyaMapView.put(minyaArray[4], MAGHAGHA);
        minyaMapView.put(minyaArray[5], MALAWI);
        minyaMapView.put(minyaArray[6], MATAY);
        minyaMapView.put(minyaArray[7], NEWMINYA);
        minyaMapView.put(minyaArray[8], SAMALUT);


        newvalleyArray = res.getStringArray(R.array.newvalley_regions);

        newvalleyMapAdd.put(BALAT, newvalleyArray[0]);
        newvalleyMapAdd.put(DAKHLA, newvalleyArray[1]);
        newvalleyMapAdd.put(FARAFRA, newvalleyArray[2]);
        newvalleyMapAdd.put(KHARGA, newvalleyArray[3]);
        newvalleyMapAdd.put(MUT, newvalleyArray[4]);
        newvalleyMapAdd.put(PARIS, newvalleyArray[5]);

        newvalleyMapView.put(newvalleyArray[0], BALAT);
        newvalleyMapView.put(newvalleyArray[1], DAKHLA);
        newvalleyMapView.put(newvalleyArray[2], FARAFRA);
        newvalleyMapView.put(newvalleyArray[3], KHARGA);
        newvalleyMapView.put(newvalleyArray[4], MUT);
        newvalleyMapView.put(newvalleyArray[5], PARIS);

        benisuefArray = res.getStringArray(R.array.benisuef_regions);

        benisuefMapAdd.put(ALFESHN, benisuefArray[0]);
        benisuefMapAdd.put(ALWASTY, benisuefArray[1]);
        benisuefMapAdd.put(BEBA, benisuefArray[2]);
        benisuefMapAdd.put(EHNASIA, benisuefArray[3]);
        benisuefMapAdd.put(NASSAR, benisuefArray[4]);
        benisuefMapAdd.put(NEWBENISUEF, benisuefArray[5]);
        benisuefMapAdd.put(SAMASTA, benisuefArray[6]);

        benisuefMapView.put(benisuefArray[0], ALFESHN);
        benisuefMapView.put(benisuefArray[1], ALWASTY);
        benisuefMapView.put(benisuefArray[2], BEBA);
        benisuefMapView.put(benisuefArray[3], EHNASIA);
        benisuefMapView.put(benisuefArray[4], NASSAR);
        benisuefMapView.put(benisuefArray[5], NEWBENISUEF);
        benisuefMapView.put(benisuefArray[6], SAMASTA);


        portsaidArray = res.getStringArray(R.array.portsaid_regions);

        portsaidMapAdd.put(ARABDISTRICT, portsaidArray[0]);
        portsaidMapAdd.put(DAWAHYDISTRICT, portsaidArray[1]);
        portsaidMapAdd.put(GANOUBDISTRICT, portsaidArray[2]);
        portsaidMapAdd.put(MANAKHDISTRICT, portsaidArray[3]);
        portsaidMapAdd.put(PORTFOUAD, portsaidArray[4]);
        portsaidMapAdd.put(SHARQDISTRICT, portsaidArray[5]);
        portsaidMapAdd.put(ZOHOURDISTRICT, portsaidArray[6]);

        portsaidMapView.put(portsaidArray[0], ARABDISTRICT);
        portsaidMapView.put(portsaidArray[1], DAWAHYDISTRICT);
        portsaidMapView.put(portsaidArray[2], GANOUBDISTRICT);
        portsaidMapView.put(portsaidArray[3], MANAKHDISTRICT);
        portsaidMapView.put(portsaidArray[4], PORTFOUAD);
        portsaidMapView.put(portsaidArray[5], SHARQDISTRICT);
        portsaidMapView.put(portsaidArray[6], ZOHOURDISTRICT);

        southsinaiArray = res.getStringArray(R.array.southsinai_regions);

        southsinaiMapAdd.put(ABURUDEIS, southsinaiArray[0]);
        southsinaiMapAdd.put(ABUZENIMAH, southsinaiArray[1]);
        southsinaiMapAdd.put(DAHAB, southsinaiArray[2]);
        southsinaiMapAdd.put(NUWEIBA, southsinaiArray[3]);
        southsinaiMapAdd.put(RASSEDR, southsinaiArray[4]);
        southsinaiMapAdd.put(SHARMALSHEIKH, southsinaiArray[5]);
        southsinaiMapAdd.put(STCATHERINE, southsinaiArray[6]);
        southsinaiMapAdd.put(TABA, southsinaiArray[7]);
        southsinaiMapAdd.put(TORSINAI, southsinaiArray[8]);

        southsinaiMapView.put(southsinaiArray[0], ABURUDEIS);
        southsinaiMapView.put(southsinaiArray[1], ABUZENIMAH);
        southsinaiMapView.put(southsinaiArray[2], DAHAB);
        southsinaiMapView.put(southsinaiArray[3], NUWEIBA);
        southsinaiMapView.put(southsinaiArray[4], RASSEDR);
        southsinaiMapView.put(southsinaiArray[5], SHARMALSHEIKH);
        southsinaiMapView.put(southsinaiArray[6], STCATHERINE);
        southsinaiMapView.put(southsinaiArray[7], TABA);
        southsinaiMapView.put(southsinaiArray[8], TORSINAI);


        damiettaArray = res.getStringArray(R.array.damietta_regions);

        damiettaMapAdd.put(EZBETALBURJ, damiettaArray[0]);
        damiettaMapAdd.put(FARESKOUR, damiettaArray[1]);
        damiettaMapAdd.put(KAFRALBATEEKH, damiettaArray[2]);
        damiettaMapAdd.put(KAFRSAAD, damiettaArray[3]);
        damiettaMapAdd.put(MITABUGHALB, damiettaArray[4]);
        damiettaMapAdd.put(NEWDAMIETTA, damiettaArray[5]);
        damiettaMapAdd.put(RASALBAR, damiettaArray[6]);
        damiettaMapAdd.put(RODAH, damiettaArray[7]);
        damiettaMapAdd.put(SARO, damiettaArray[8]);
        damiettaMapAdd.put(ZARQA, damiettaArray[9]);

        damiettaMapView.put(damiettaArray[0], EZBETALBURJ);
        damiettaMapView.put(damiettaArray[1], FARESKOUR);
        damiettaMapView.put(damiettaArray[2], KAFRALBATEEKH);
        damiettaMapView.put(damiettaArray[3], KAFRSAAD);
        damiettaMapView.put(damiettaArray[4], MITABUGHALB);
        damiettaMapView.put(damiettaArray[5], NEWDAMIETTA);
        damiettaMapView.put(damiettaArray[6], RASALBAR);
        damiettaMapView.put(damiettaArray[7], RODAH);
        damiettaMapView.put(damiettaArray[8], SARO);
        damiettaMapView.put(damiettaArray[9], ZARQA);

        sohagArray = res.getStringArray(R.array.sohag_regions);

        sohagMapAdd.put(AKHMIM, sohagArray[0]);
        sohagMapAdd.put(ALASIRAT, sohagArray[1]);
        sohagMapAdd.put(DARESSALAM, sohagArray[2]);
        sohagMapAdd.put(GIRGA, sohagArray[3]);
        sohagMapAdd.put(JUHAYNAH, sohagArray[4]);
        sohagMapAdd.put(MARAGHA, sohagArray[5]);
        sohagMapAdd.put(MONASHAA, sohagArray[6]);
        sohagMapAdd.put(SAKALTAH, sohagArray[7]);
        sohagMapAdd.put(TAHTA, sohagArray[8]);
        sohagMapAdd.put(TAMA, sohagArray[9]);

        sohagMapView.put(sohagArray[0], AKHMIM);
        sohagMapView.put(sohagArray[1], ALASIRAT);
        sohagMapView.put(sohagArray[2], DARESSALAM);
        sohagMapView.put(sohagArray[3], GIRGA);
        sohagMapView.put(sohagArray[4], JUHAYNAH);
        sohagMapView.put(sohagArray[5], MARAGHA);
        sohagMapView.put(sohagArray[6], MONASHAA);
        sohagMapView.put(sohagArray[7], SAKALTAH);
        sohagMapView.put(sohagArray[8], TAHTA);
        sohagMapView.put(sohagArray[9], TAMA);

        northsinaiArray = res.getStringArray(R.array.northsinai_regions);

        northsinaiMapAdd.put(ARISH, northsinaiArray[0]);
        northsinaiMapAdd.put(BIRALABED, northsinaiArray[1]);
        northsinaiMapAdd.put(HASANA, northsinaiArray[2]);
        northsinaiMapAdd.put(NAKHL, northsinaiArray[3]);
        northsinaiMapAdd.put(RAFAH, northsinaiArray[4]);
        northsinaiMapAdd.put(SHEIKHZOWEYED, northsinaiArray[5]);

        northsinaiMapView.put(northsinaiArray[0], ARISH);
        northsinaiMapView.put(northsinaiArray[1], BIRALABED);
        northsinaiMapView.put(northsinaiArray[2], HASANA);
        northsinaiMapView.put(northsinaiArray[3], NAKHL);
        northsinaiMapView.put(northsinaiArray[4], RAFAH);
        northsinaiMapView.put(northsinaiArray[5], SHEIKHZOWEYED);

        qenaArray = res.getStringArray(R.array.qena_regions);

        qenaMapAdd.put(ABUTISHT, qenaArray[0]);
        qenaMapAdd.put(FARSHOUT, qenaArray[1]);
        qenaMapAdd.put(KEFT, qenaArray[2]);
        qenaMapAdd.put(NAGHAMMADI, qenaArray[3]);
        qenaMapAdd.put(NAKADA, qenaArray[4]);
        qenaMapAdd.put(KOOS, qenaArray[5]);
        qenaMapAdd.put(ELSAMATA, qenaArray[6]);
        qenaMapAdd.put(DESHNA, qenaArray[7]);
        qenaMapAdd.put(WAKF, qenaArray[8]);
        qenaMapAdd.put(ELBARAHAMA, qenaArray[9]);
        qenaMapAdd.put(ELASHRAF, qenaArray[10]);
        qenaMapAdd.put(QENACITY, qenaArray[11]);
        qenaMapAdd.put(ALKLAHIL, qenaArray[12]);

        qenaMapView.put(qenaArray[0], ABUTISHT);
        qenaMapView.put(qenaArray[1], FARSHOUT);
        qenaMapView.put(qenaArray[2], KEFT);
        qenaMapView.put(qenaArray[3], NAGHAMMADI);
        qenaMapView.put(qenaArray[4], NAKADA);
        qenaMapView.put(qenaArray[5], KOOS);
        qenaMapView.put(qenaArray[6], ELSAMATA);
        qenaMapView.put(qenaArray[7], DESHNA);
        qenaMapView.put(qenaArray[8], WAKF);
        qenaMapView.put(qenaArray[9], ELBARAHAMA);
        qenaMapView.put(qenaArray[10], ELASHRAF);
        qenaMapView.put(qenaArray[11], QENACITY);
        qenaMapView.put(qenaArray[12], ALKLAHIL);

        kafralsheikhArray = res.getStringArray(R.array.kafralsheikh_regions);

        kafralsheikhMapAdd.put(MOTOBAS, kafralsheikhArray[0]);
        kafralsheikhMapAdd.put(QALEEN, kafralsheikhArray[1]);
        kafralsheikhMapAdd.put(RIYADH, kafralsheikhArray[2]);
        kafralsheikhMapAdd.put(SIDISALEM, kafralsheikhArray[3]);
        kafralsheikhMapAdd.put(KAFRALSHEIKHCITY, kafralsheikhArray[4]);
        kafralsheikhMapAdd.put(ELHAMOL, kafralsheikhArray[5]);
        kafralsheikhMapAdd.put(BELA, kafralsheikhArray[6]);
        kafralsheikhMapAdd.put(BALTEEM, kafralsheikhArray[7]);
        kafralsheikhMapAdd.put(SAKHA, kafralsheikhArray[8]);
        kafralsheikhMapAdd.put(SEDIGHAZI, kafralsheikhArray[9]);

        kafralsheikhMapView.put(kafralsheikhArray[0], MOTOBAS);
        kafralsheikhMapView.put(kafralsheikhArray[1], QALEEN);
        kafralsheikhMapView.put(kafralsheikhArray[2], RIYADH);
        kafralsheikhMapView.put(kafralsheikhArray[3], SIDISALEM);
        kafralsheikhMapView.put(kafralsheikhArray[4], KAFRALSHEIKHCITY);
        kafralsheikhMapView.put(kafralsheikhArray[5], ELHAMOL);
        kafralsheikhMapView.put(kafralsheikhArray[6], BELA);
        kafralsheikhMapView.put(kafralsheikhArray[7], BALTEEM);
        kafralsheikhMapView.put(kafralsheikhArray[8], SAKHA);
        kafralsheikhMapView.put(kafralsheikhArray[9], SEDIGHAZI);

        matruhArray = res.getStringArray(R.array.matruh_regions);

        matruhMapAdd.put(ALAMEIN, matruhArray[0]);
        matruhMapAdd.put(BARANY, matruhArray[1]);
        matruhMapAdd.put(DABAA, matruhArray[2]);
        matruhMapAdd.put(HAMMAM, matruhArray[3]);
        matruhMapAdd.put(MARINAELALAMEIN, matruhArray[4]);
        matruhMapAdd.put(MARSAMATROUH, matruhArray[5]);
        matruhMapAdd.put(NAGELA, matruhArray[6]);
        matruhMapAdd.put(SALLOUM, matruhArray[7]);
        matruhMapAdd.put(SIWA, matruhArray[8]);
        matruhMapAdd.put(RASELHEKMA, matruhArray[9]);
        matruhMapAdd.put(SEDIABDELRAHMAN, matruhArray[10]);

        matruhMapView.put(matruhArray[0], ALAMEIN);
        matruhMapView.put(matruhArray[1], BARANY);
        matruhMapView.put(matruhArray[2], DABAA);
        matruhMapView.put(matruhArray[3], HAMMAM);
        matruhMapView.put(matruhArray[4], MARINAELALAMEIN);
        matruhMapView.put(matruhArray[5], MARSAMATROUH);
        matruhMapView.put(matruhArray[6], NAGELA);
        matruhMapView.put(matruhArray[7], SALLOUM);
        matruhMapView.put(matruhArray[8], SIWA);
        matruhMapView.put(matruhArray[9], RASELHEKMA);
        matruhMapView.put(matruhArray[10], SEDIABDELRAHMAN);


    }
}
